### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by karussell** [Janekdererste/gh-maps-react#11]
- adding start and end points
 - insert? (dragging route?)
 - delete

**Comment by Janekdererste** [comment]
This was solved in 8bbda9ff235d33bccc742f0eef9a09cde4240f98 and ec0842e12267fbe5e3b4b1070b07883385e7dc2e . 

Tested dragging the route for new via-Points but found it not very intuitive. One can now add markers by:
- clicking on the map, which fills the currently available waypoints.
- right-clicking and selecting from, to or via from a context menu. This logic adds via points if none are in the current search
- Typing in a search box and selecting a geocoding result

**Comment by easbar** [comment]
> Tested dragging the route for new via-Points but found it not very intuitive.

Do you mean it is hard to implement or not useful? I thought this would be nice, because with this input the order of the via points is clear. Otherwise we have to 'guess' where (in which order) the new via point shall be inserted (i.e. before or after other via points). This is what we do currently. How do you determine the order?

**Comment by Janekdererste** [comment]
> I thought this would be nice, because with this input the order of the via points is clear. 

Good point. I tried the dragging away from the current path and generating a new via point. It somehow didn't fell very intuitive to use. I think it would have to feel a little more like in google maps where there is a dot moving along the path when the mouse is moved along it. Implementing this felt like too much work for the 0.1 version and I'd like to check in about how to do it.

> How do you determine the order?

Currently, via points are inserted on the last position before the destination point. If there are undefined via points (because the user has selected 'add point' in the search bar but not selected a point yet) the first undefined point is set, when 'via here' from the context menu is selected. 

I had a look at the current graphhopper maps implementation of selecting via points and thought I should talk to you guys before I imlement anything more complicated than what is described above. Obviously someone has already thought about the problem and I didn't want to reinvent the wheel.

**Comment by karussell** [comment]
> Implementing this felt like too much work for the 0.1 version and I'd like to check in about how to do it.

:+1: I think I saw this here:

https://github.com/Kasheftin/graphhopper-frontend

Or probably here (but there is no open source license associated):

https://github.com/Kasheftin/RoutePlanner
https://github.com/Kasheftin/route-planner-vue
